spring:
  application:
    name: eureka_server

server:
  port: 8761

eureka:
  instance:
    hostname: eureka_server

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka_server:8761/eureka/
